// Code generated by SQLBoiler 4.14.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Users          string
	Bookings       string
	Customers      string
	Films          string
	GorpMigrations string
	ReservedSeat   string
	Rooms          string
	Screenings     string
	Seats          string
}{
	Users:          "Users",
	Bookings:       "bookings",
	Customers:      "customers",
	Films:          "films",
	GorpMigrations: "gorp_migrations",
	ReservedSeat:   "reserved_seat",
	Rooms:          "rooms",
	Screenings:     "screenings",
	Seats:          "seats",
}
