// Code generated by SQLBoiler 4.14.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// Film is an object representing the database table.
type Film struct {
	ID        int    `boil:"id" json:"id" toml:"id" yaml:"id"`
	Name      string `boil:"name" json:"name" toml:"name" yaml:"name"`
	LengthMin int    `boil:"length_min" json:"length_min" toml:"length_min" yaml:"length_min"`

	R *filmR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L filmL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var FilmColumns = struct {
	ID        string
	Name      string
	LengthMin string
}{
	ID:        "id",
	Name:      "name",
	LengthMin: "length_min",
}

var FilmTableColumns = struct {
	ID        string
	Name      string
	LengthMin string
}{
	ID:        "films.id",
	Name:      "films.name",
	LengthMin: "films.length_min",
}

// Generated where

var FilmWhere = struct {
	ID        whereHelperint
	Name      whereHelperstring
	LengthMin whereHelperint
}{
	ID:        whereHelperint{field: "`films`.`id`"},
	Name:      whereHelperstring{field: "`films`.`name`"},
	LengthMin: whereHelperint{field: "`films`.`length_min`"},
}

// FilmRels is where relationship names are stored.
var FilmRels = struct {
	Screenings string
}{
	Screenings: "Screenings",
}

// filmR is where relationships are stored.
type filmR struct {
	Screenings ScreeningSlice `boil:"Screenings" json:"Screenings" toml:"Screenings" yaml:"Screenings"`
}

// NewStruct creates a new relationship struct
func (*filmR) NewStruct() *filmR {
	return &filmR{}
}

func (r *filmR) GetScreenings() ScreeningSlice {
	if r == nil {
		return nil
	}
	return r.Screenings
}

// filmL is where Load methods for each relationship are stored.
type filmL struct{}

var (
	filmAllColumns            = []string{"id", "name", "length_min"}
	filmColumnsWithoutDefault = []string{"name", "length_min"}
	filmColumnsWithDefault    = []string{"id"}
	filmPrimaryKeyColumns     = []string{"id"}
	filmGeneratedColumns      = []string{}
)

type (
	// FilmSlice is an alias for a slice of pointers to Film.
	// This should almost always be used instead of []Film.
	FilmSlice []*Film
	// FilmHook is the signature for custom Film hook methods
	FilmHook func(context.Context, boil.ContextExecutor, *Film) error

	filmQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	filmType                 = reflect.TypeOf(&Film{})
	filmMapping              = queries.MakeStructMapping(filmType)
	filmPrimaryKeyMapping, _ = queries.BindMapping(filmType, filmMapping, filmPrimaryKeyColumns)
	filmInsertCacheMut       sync.RWMutex
	filmInsertCache          = make(map[string]insertCache)
	filmUpdateCacheMut       sync.RWMutex
	filmUpdateCache          = make(map[string]updateCache)
	filmUpsertCacheMut       sync.RWMutex
	filmUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var filmAfterSelectHooks []FilmHook

var filmBeforeInsertHooks []FilmHook
var filmAfterInsertHooks []FilmHook

var filmBeforeUpdateHooks []FilmHook
var filmAfterUpdateHooks []FilmHook

var filmBeforeDeleteHooks []FilmHook
var filmAfterDeleteHooks []FilmHook

var filmBeforeUpsertHooks []FilmHook
var filmAfterUpsertHooks []FilmHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Film) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range filmAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Film) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range filmBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Film) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range filmAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Film) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range filmBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Film) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range filmAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Film) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range filmBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Film) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range filmAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Film) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range filmBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Film) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range filmAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddFilmHook registers your hook function for all future operations.
func AddFilmHook(hookPoint boil.HookPoint, filmHook FilmHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		filmAfterSelectHooks = append(filmAfterSelectHooks, filmHook)
	case boil.BeforeInsertHook:
		filmBeforeInsertHooks = append(filmBeforeInsertHooks, filmHook)
	case boil.AfterInsertHook:
		filmAfterInsertHooks = append(filmAfterInsertHooks, filmHook)
	case boil.BeforeUpdateHook:
		filmBeforeUpdateHooks = append(filmBeforeUpdateHooks, filmHook)
	case boil.AfterUpdateHook:
		filmAfterUpdateHooks = append(filmAfterUpdateHooks, filmHook)
	case boil.BeforeDeleteHook:
		filmBeforeDeleteHooks = append(filmBeforeDeleteHooks, filmHook)
	case boil.AfterDeleteHook:
		filmAfterDeleteHooks = append(filmAfterDeleteHooks, filmHook)
	case boil.BeforeUpsertHook:
		filmBeforeUpsertHooks = append(filmBeforeUpsertHooks, filmHook)
	case boil.AfterUpsertHook:
		filmAfterUpsertHooks = append(filmAfterUpsertHooks, filmHook)
	}
}

// OneG returns a single film record from the query using the global executor.
func (q filmQuery) OneG(ctx context.Context) (*Film, error) {
	return q.One(ctx, boil.GetContextDB())
}

// One returns a single film record from the query.
func (q filmQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Film, error) {
	o := &Film{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for films")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// AllG returns all Film records from the query using the global executor.
func (q filmQuery) AllG(ctx context.Context) (FilmSlice, error) {
	return q.All(ctx, boil.GetContextDB())
}

// All returns all Film records from the query.
func (q filmQuery) All(ctx context.Context, exec boil.ContextExecutor) (FilmSlice, error) {
	var o []*Film

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Film slice")
	}

	if len(filmAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountG returns the count of all Film records in the query using the global executor
func (q filmQuery) CountG(ctx context.Context) (int64, error) {
	return q.Count(ctx, boil.GetContextDB())
}

// Count returns the count of all Film records in the query.
func (q filmQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count films rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table using the global executor.
func (q filmQuery) ExistsG(ctx context.Context) (bool, error) {
	return q.Exists(ctx, boil.GetContextDB())
}

// Exists checks if the row exists in the table.
func (q filmQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if films exists")
	}

	return count > 0, nil
}

// Screenings retrieves all the screening's Screenings with an executor.
func (o *Film) Screenings(mods ...qm.QueryMod) screeningQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("`screenings`.`film_id`=?", o.ID),
	)

	return Screenings(queryMods...)
}

// LoadScreenings allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (filmL) LoadScreenings(ctx context.Context, e boil.ContextExecutor, singular bool, maybeFilm interface{}, mods queries.Applicator) error {
	var slice []*Film
	var object *Film

	if singular {
		var ok bool
		object, ok = maybeFilm.(*Film)
		if !ok {
			object = new(Film)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeFilm)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeFilm))
			}
		}
	} else {
		s, ok := maybeFilm.(*[]*Film)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeFilm)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeFilm))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &filmR{}
		}
		args = append(args, object.ID)
	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &filmR{}
			}

			for _, a := range args {
				if a == obj.ID {
					continue Outer
				}
			}

			args = append(args, obj.ID)
		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`screenings`),
		qm.WhereIn(`screenings.film_id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load screenings")
	}

	var resultSlice []*Screening
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice screenings")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on screenings")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for screenings")
	}

	if len(screeningAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.Screenings = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &screeningR{}
			}
			foreign.R.Film = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.FilmID {
				local.R.Screenings = append(local.R.Screenings, foreign)
				if foreign.R == nil {
					foreign.R = &screeningR{}
				}
				foreign.R.Film = local
				break
			}
		}
	}

	return nil
}

// AddScreeningsG adds the given related objects to the existing relationships
// of the film, optionally inserting them as new records.
// Appends related to o.R.Screenings.
// Sets related.R.Film appropriately.
// Uses the global database handle.
func (o *Film) AddScreeningsG(ctx context.Context, insert bool, related ...*Screening) error {
	return o.AddScreenings(ctx, boil.GetContextDB(), insert, related...)
}

// AddScreenings adds the given related objects to the existing relationships
// of the film, optionally inserting them as new records.
// Appends related to o.R.Screenings.
// Sets related.R.Film appropriately.
func (o *Film) AddScreenings(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Screening) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.FilmID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE `screenings` SET %s WHERE %s",
				strmangle.SetParamNames("`", "`", 0, []string{"film_id"}),
				strmangle.WhereClause("`", "`", 0, screeningPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.FilmID = o.ID
		}
	}

	if o.R == nil {
		o.R = &filmR{
			Screenings: related,
		}
	} else {
		o.R.Screenings = append(o.R.Screenings, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &screeningR{
				Film: o,
			}
		} else {
			rel.R.Film = o
		}
	}
	return nil
}

// Films retrieves all the records using an executor.
func Films(mods ...qm.QueryMod) filmQuery {
	mods = append(mods, qm.From("`films`"))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"`films`.*"})
	}

	return filmQuery{q}
}

// FindFilmG retrieves a single record by ID.
func FindFilmG(ctx context.Context, iD int, selectCols ...string) (*Film, error) {
	return FindFilm(ctx, boil.GetContextDB(), iD, selectCols...)
}

// FindFilm retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindFilm(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*Film, error) {
	filmObj := &Film{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `films` where `id`=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, filmObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from films")
	}

	if err = filmObj.doAfterSelectHooks(ctx, exec); err != nil {
		return filmObj, err
	}

	return filmObj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *Film) InsertG(ctx context.Context, columns boil.Columns) error {
	return o.Insert(ctx, boil.GetContextDB(), columns)
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Film) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no films provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(filmColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	filmInsertCacheMut.RLock()
	cache, cached := filmInsertCache[key]
	filmInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			filmAllColumns,
			filmColumnsWithDefault,
			filmColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(filmType, filmMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(filmType, filmMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `films` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `films` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `films` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, filmPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into films")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == filmMapping["id"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for films")
	}

CacheNoHooks:
	if !cached {
		filmInsertCacheMut.Lock()
		filmInsertCache[key] = cache
		filmInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// UpdateG a single Film record using the global executor.
// See Update for more documentation.
func (o *Film) UpdateG(ctx context.Context, columns boil.Columns) (int64, error) {
	return o.Update(ctx, boil.GetContextDB(), columns)
}

// Update uses an executor to update the Film.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Film) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	filmUpdateCacheMut.RLock()
	cache, cached := filmUpdateCache[key]
	filmUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			filmAllColumns,
			filmPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update films, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `films` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, filmPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(filmType, filmMapping, append(wl, filmPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update films row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for films")
	}

	if !cached {
		filmUpdateCacheMut.Lock()
		filmUpdateCache[key] = cache
		filmUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAllG updates all rows with the specified column values.
func (q filmQuery) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return q.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values.
func (q filmQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for films")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for films")
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (o FilmSlice) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return o.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o FilmSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), filmPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `films` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, filmPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in film slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all film")
	}
	return rowsAff, nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *Film) UpsertG(ctx context.Context, updateColumns, insertColumns boil.Columns) error {
	return o.Upsert(ctx, boil.GetContextDB(), updateColumns, insertColumns)
}

var mySQLFilmUniqueColumns = []string{
	"id",
	"name",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Film) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no films provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(filmColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLFilmUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	filmUpsertCacheMut.RLock()
	cache, cached := filmUpsertCache[key]
	filmUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			filmAllColumns,
			filmColumnsWithDefault,
			filmColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			filmAllColumns,
			filmPrimaryKeyColumns,
		)

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("models: unable to upsert films, could not build update column list")
		}

		ret = strmangle.SetComplement(ret, nzUniques)
		cache.query = buildUpsertQueryMySQL(dialect, "`films`", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `films` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(filmType, filmMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(filmType, filmMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for films")
	}

	var lastID int64
	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == filmMapping["id"] {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(filmType, filmMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "models: unable to retrieve unique values for films")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, nzUniqueCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for films")
	}

CacheNoHooks:
	if !cached {
		filmUpsertCacheMut.Lock()
		filmUpsertCache[key] = cache
		filmUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// DeleteG deletes a single Film record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *Film) DeleteG(ctx context.Context) (int64, error) {
	return o.Delete(ctx, boil.GetContextDB())
}

// Delete deletes a single Film record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Film) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no Film provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), filmPrimaryKeyMapping)
	sql := "DELETE FROM `films` WHERE `id`=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from films")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for films")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

func (q filmQuery) DeleteAllG(ctx context.Context) (int64, error) {
	return q.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all matching rows.
func (q filmQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no filmQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from films")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for films")
	}

	return rowsAff, nil
}

// DeleteAllG deletes all rows in the slice.
func (o FilmSlice) DeleteAllG(ctx context.Context) (int64, error) {
	return o.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o FilmSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(filmBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), filmPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `films` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, filmPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from film slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for films")
	}

	if len(filmAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *Film) ReloadG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: no Film provided for reload")
	}

	return o.Reload(ctx, boil.GetContextDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Film) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindFilm(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *FilmSlice) ReloadAllG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: empty FilmSlice provided for reload all")
	}

	return o.ReloadAll(ctx, boil.GetContextDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *FilmSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := FilmSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), filmPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `films`.* FROM `films` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, filmPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in FilmSlice")
	}

	*o = slice

	return nil
}

// FilmExistsG checks if the Film row exists.
func FilmExistsG(ctx context.Context, iD int) (bool, error) {
	return FilmExists(ctx, boil.GetContextDB(), iD)
}

// FilmExists checks if the Film row exists.
func FilmExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `films` where `id`=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if films exists")
	}

	return exists, nil
}

// Exists checks if the Film row exists.
func (o *Film) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return FilmExists(ctx, exec, o.ID)
}
